const API = "https://soccer-carpool-roster.awtrescue-org.chatgpt.site/api/carpool";
const ADMIN_API = "https://soccer-carpool-roster.awtrescue-org.chatgpt.site/api/admin";
const PROFILE_API = "https://soccer-carpool-roster.awtrescue-org.chatgpt.site/api/profile";
const firebaseConfig={apiKey:"AIzaSyAnzyxw5whft5kgeZKs1P3NCf-8QlSK-T8",authDomain:"soccer-rideshare.firebaseapp.com",projectId:"soccer-rideshare",storageBucket:"soccer-rideshare.firebasestorage.app",messagingSenderId:"704817990804",appId:"1:704817990804:web:59c66c9285397a59883881"};
const root = document.querySelector("#app");
let currentUser=null,idToken="",profile=null;
let data = { events: [], players: [], drivers: [], rides: [], driverProfiles: [], directory: [], locations: [] };
let selected = null;

const h = (value = "") => String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const initials = name => name.split(/\s+/).map(n => n[0]).join("").slice(0,2).toUpperCase();
const direction = value => value === "to" ? "Drop-off" : value === "from" ? "Pickup / ride home" : "Round trip";
const shortDate = value => new Date(value + "T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"});
const longDate = value => new Date(value + "T12:00:00").toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"});
const headers = () => ({"content-type":"application/json","authorization":`Bearer ${idToken}`});

async function api(method = "GET", body) {
  const response = await fetch(API, { method, headers: headers(), body: body ? JSON.stringify(body) : undefined });
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.error || "Could not update the roster.");
  return payload;
}

function login(message = "") {
  root.innerHTML = `<main class="pinPage"><section class="pinCard"><span class="brandMark">SC</span><p class="eyebrow">SOCCER CARPOOL</p><h1>Team sign-in</h1><p>Use your Google account to open the private team roster.</p>${message ? `<div class="notice error" role="alert">${h(message)}</div>` : ""}<button class="googleButton" id="googleLogin"><span>G</span>Continue with Google</button><small class="privacyNote">Only administrator-approved parents can see team information.</small></section></main>`;
  document.querySelector("#googleLogin").addEventListener("click",async()=>{try{await firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(error){login(error.message)}});
}

function pending(){root.innerHTML=`<main class="pinPage"><section class="pinCard pendingCard"><span class="brandMark">SC</span><p class="eyebrow">SIGNED IN AS ${h(profile.email)}</p><h1>Approval pending</h1><p>Complete your parent profile, then an administrator can approve access to the team roster.</p><div class="pendingActions"><button class="primary" data-profile>${profile.homePickup?"Edit profile":"Complete profile"}</button><button class="outline" data-admin>Administrator</button><button class="textButton" data-signout>Sign out</button></div></section></main>`;document.querySelector("[data-profile]").addEventListener("click",openProfile);document.querySelector("[data-admin]").addEventListener("click",openAdmin);document.querySelector("[data-signout]").addEventListener("click",()=>firebase.auth().signOut())}

function render(notice = "") {
  const event = data.events.find(item => item.id === selected) || data.events[0] || null;
  if (event) selected = event.id;
  const drivers = data.drivers.filter(item => item.eventId === selected);
  const rides = data.rides.filter(item => item.eventId === selected);
  const players = new Map(data.players.map(item => [item.id,item]));
  const locations = new Map((data.locations||[]).map(item => [item.id,item]));
  const eventLocation = event ? locations.get(event.locationId) : null;
  const need = rides.filter(item => !item.driverId).length;
  const seats = drivers.reduce((sum,item)=>sum+item.capacity,0);
  root.innerHTML = `
    <header class="topbar"><div class="brand"><span class="brandMark">SC</span><span><b>Soccer Carpool</b><small>Team ride board</small></span></div><div class="topActions"><button class="outline small" data-directory>Families</button><button class="outline small" data-profile>My profile</button><button class="outline small" data-admin>Admin</button><button class="outline small" data-signout>Sign out</button></div></header>
    <section class="hero"><div><p class="eyebrow">NO PLAYER LEFT BEHIND</p><h1>Rides sorted.<br><em>Game on.</em></h1><p class="heroCopy">One shared place for families to offer seats, request a ride, and see exactly who is riding with whom.</p><div class="heroActions"><button class="primary" data-open="driver" ${data.events.length?"":"disabled"}>I can drive</button><button class="secondary" data-open="ride" ${data.events.length?"":"disabled"}>My player needs a ride</button></div></div>
      <div class="scoreCard"><div class="ball">⚽</div><p>${event ? "NEXT "+event.eventType.toUpperCase() : "NEXT TEAM EVENT"}</p><strong>${event ? h(longDate(event.eventDate)) : "Schedule pending"}</strong><span>${event ? h("Starts "+event.departTime+" · "+event.location) : "Check back for the next event"}</span></div>
    </section>
    <section class="workspace"><div class="sectionHeading"><div><p class="eyebrow">CARPOOL BOARD</p><h2>Games & practices</h2></div><div class="summaryPills"><span><b>${need}</b> need a seat</span><span><b>${seats}</b> seats offered</span></div></div>
      ${notice ? `<div class="notice">${h(notice)}</div>` : ""}
      ${!data.events.length ? `<div class="empty"><div>⚽</div><h3>The schedule is coming soon</h3><p>An administrator will add the next game or practice. Once it appears, families can offer seats or request a ride.</p></div>` : `
        <div class="eventTabs" role="tablist">${data.events.map(item=>`<button data-event="${item.id}" class="${item.id===selected?"active":""}"><small><span class="eventType ${item.eventType}">${h(item.eventType)}</span>${h(shortDate(item.eventDate))}</small><b>${h(item.title)}</b><span>${h(item.departTime)}</span></button>`).join("")}</div>
        <div class="eventHeader"><div><p>${h(longDate(event.eventDate))} · Starts ${h(event.departTime)}</p><h3>${h(event.title)}</h3>${eventLocation?`<a class="mapLink" href="${h(eventLocation.mapUrl)}" target="_blank" rel="noreferrer">📍 ${h(event.location)}</a>`:`<span>${h(event.location)}</span>`}</div><div class="eventButtons"><button class="outline" data-open="driver">Offer seats</button><button class="primary" data-open="ride">Request ride</button></div></div>
        <div class="boardGrid">
          <section class="boardColumn"><div class="columnTitle"><div><span class="dot green"></span><h3>Drivers</h3></div><b>${drivers.length}</b></div>
            ${drivers.length ? drivers.map(driver=>{
              const assigned=rides.filter(ride=>ride.driverId===driver.id),remaining=Math.max(0,driver.capacity-assigned.length);
              return `<article class="card"><div class="cardTop"><div class="avatar">${h(initials(driver.parentName))}</div><div><h4>${h(driver.parentName)}</h4><p>${h(direction(driver.direction))}</p></div><span class="badge">${remaining} ${remaining===1?"seat":"seats"} open</span></div>${assigned.length?`<div class="passengers"><small>RIDING WITH ${h(driver.parentName.split(" ")[0].toUpperCase())}</small>${assigned.map(ride=>`<span>✓ ${h(players.get(ride.playerId)?.name||"Player")}</span>`).join("")}</div>${driver.isMine?`<button class="routeButton" data-route="${driver.id}">🧭 Open pickup route</button>`:""}`:""}${driver.notes?`<p>“${h(driver.notes)}”</p>`:""}</article>`;
            }).join("") : `<div class="empty">No drivers yet. Be the first to offer seats.</div>`}
          </section>
          <section class="boardColumn"><div class="columnTitle"><div><span class="dot amber"></span><h3>Ride requests</h3></div><b>${rides.length}</b></div>
            ${rides.length ? rides.map(ride=>{
              const player=players.get(ride.playerId),pickup=locations.get(ride.locationId),options=drivers.filter(driver=>driver.id===ride.driverId||((driver.direction===ride.direction||driver.direction==="roundtrip")&&rides.filter(r=>r.driverId===driver.id).length<driver.capacity));
              return `<article class="card ${ride.driverId?"assigned":""}"><div class="cardTop"><div class="avatar player">${h(initials(player?.name||"P"))}</div><div><h4>${h(player?.name||"Player")}</h4><p>${h(direction(ride.direction))}</p></div><span class="badge ${ride.driverId?"":"waiting"}">${ride.driverId?"Matched":"Needs ride"}</span></div>${pickup?`<a class="mapLink rideLocation" href="${h(pickup.mapUrl)}" target="_blank" rel="noreferrer">📍 ${h(pickup.name)}</a>`:`<div class="privatePickup">🔒 ${h(ride.pickupLabel||"Private pickup address")}</div>`}<label class="assign">Assigned driver<select data-assign="${ride.id}"><option value="">Unassigned</option>${options.map(driver=>`<option value="${driver.id}" ${driver.id===ride.driverId?"selected":""}>${h(driver.parentName)}</option>`).join("")}</select></label></article>`;
            }).join("") : `<div class="empty">Everyone has transportation for this event.</div>`}
          </section>
        </div>`}
    </section><footer><span>Soccer Carpool Roster</span><p>Clear rides. Happy families. Players on the pitch.</p></footer>`;
  bind();
}

function bind() {
  document.querySelector("[data-admin]")?.addEventListener("click",openAdmin);
  document.querySelector("[data-profile]")?.addEventListener("click",openProfile);
  document.querySelector("[data-directory]")?.addEventListener("click",openDirectory);
  document.querySelector("[data-signout]")?.addEventListener("click",()=>firebase.auth().signOut());
  document.querySelectorAll("[data-open]").forEach(button => button.addEventListener("click",()=>openModal(button.dataset.open)));
  document.querySelectorAll("[data-event]").forEach(button => button.addEventListener("click",()=>{selected=Number(button.dataset.event);render()}));
  document.querySelectorAll("[data-assign]").forEach(select => select.addEventListener("change",async()=>{
    try { await api("POST",{action:"assign",rideId:select.dataset.assign,driverId:select.value}); await refresh("Player assignment updated."); }
    catch(error){ alert(error.message); }
  }));
  document.querySelectorAll("[data-route]").forEach(button=>button.addEventListener("click",async()=>{const popup=window.open("","_blank");try{const result=await api("POST",{action:"open_route",driverId:button.dataset.route});if(popup)popup.location.href=result.url;else window.location.href=result.url;const response=await fetch(PROFILE_API,{cache:"no-store",headers:{authorization:`Bearer ${idToken}`}});if(response.ok)profile=(await response.json()).profile}catch(error){popup?.close();alert(error.message)}}));
}

const adminHelp = {
  schedule:{title:"Schedule",columns:"type, title, date, start_time, location, notes",sample:"practice,Tuesday practice,2026-09-08,17:15,Memorial Field,Bring water"},
  players:{title:"Kid names",columns:"player, guardian, phone",sample:"Alex Rivera,Jamie Rivera,206-555-0142"},
  drivers:{title:"Driver info",columns:"driver, phone, capacity, notes",sample:"Jamie Rivera,206-555-0142,4,Can meet at school"},
  locations:{title:"Locations",columns:"name, map_url",sample:"Battle Point Park,https://maps.app.goo.gl/example"}
};
function parseCsv(source){
  const rows=[];let row=[],field="",quoted=false;
  for(let i=0;i<source.length;i++){const ch=source[i];if(ch==='"'){if(quoted&&source[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(field.trim());field=""}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&source[i+1]==='\n')i++;row.push(field.trim());if(row.some(Boolean))rows.push(row);row=[];field=""}else field+=ch}
  row.push(field.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)throw new Error("The CSV needs a header row and at least one data row.");
  const names=rows[0].map(value=>value.toLowerCase().replace(/^\uFEFF/,""));return rows.slice(1).map(values=>Object.fromEntries(names.map((name,index)=>[name,values[index]||""])));
}
const accessAction=action=>action==="route_opened"?"Pickup route opened":action==="admin_revealed"?"Administrator revealed address":"Address updated";
const accessHistory=logs=>logs?.length?`<section class="accessHistory"><h3>Address activity</h3>${logs.slice(0,10).map(log=>`<div><b>${h(accessAction(log.action))}</b><span>${h(log.actorEmail)} · ${h(new Date((log.createdAt||"").replace(" ","T")+"Z").toLocaleString())}</span><small>${h(log.reason)}</small></div>`).join("")}</section>`:"";
function openAdmin(){
  document.body.insertAdjacentHTML("beforeend",`<div class="modalBackdrop" id="adminModal"><div class="modal adminModal"><button class="close" aria-label="Close">×</button><p class="eyebrow">PRIVATE TEAM TOOLS</p><h2>Administrator</h2><div id="adminBody"><form id="adminLogin"><p class="adminIntro">Enter the administrator password to approve parents and load team data. This is separate from Google sign-in.</p><label>Administrator password<input name="password" type="password" required autofocus></label><div id="adminNotice"></div><button class="primary submit">Open admin tools</button></form></div></div></div>`);
  const modal=document.querySelector("#adminModal"),body=modal.querySelector("#adminBody");let password="",counts={schedule:0,players:0,drivers:0,locations:0},profiles=[],records={schedule:[],players:[],drivers:[],locations:[]},kind="schedule",view="manage",editing=null,confirming=false,notice="",privateAddress=null,addressLogs=[];
  const close=()=>modal.remove();modal.querySelector(".close").addEventListener("click",close);modal.addEventListener("click",event=>{if(event.target===modal)close()});
  const adminApi=async(method="GET",payload)=>{const response=await fetch(ADMIN_API,{method,headers:{"content-type":"application/json","x-admin-password":password},body:payload?JSON.stringify(payload):undefined});const result=await response.json();if(!response.ok)throw new Error(result.error||"Admin request failed");return result};
  const apply=result=>{counts=result.counts;profiles=result.profiles||[];records=result.records||records};
  const list=()=>kind==="parents"?profiles:records[kind];
  const title=item=>kind==="schedule"?item.title:kind==="players"||kind==="locations"?item.name:kind==="drivers"?item.parentName:item.displayName;
  const meta=item=>kind==="schedule"?`${item.eventType} · ${item.eventDate} · ${item.departTime}`:kind==="players"?`${item.guardian} · ${item.phone}`:kind==="drivers"?`${item.capacity} seats · ${item.phone}`:kind==="locations"?"Google Maps destination":`${item.email} · ${item.approved?"Approved":"Pending"}`;
  const value=(item,key)=>h(item?.[key]??"");
  const editor=()=>{const item=editing||{};if(kind==="parents")return `<div class="parentReview"><dl><dt>Name</dt><dd>${value(item,"displayName")}</dd><dt>Email</dt><dd>${value(item,"email")}</dd><dt>Phone</dt><dd>${value(item,"phone")||"Not provided"}</dd><dt>Home address</dt><dd>${privateAddress?h(privateAddress.homePickup||"Not provided"):"Private — reveal access is logged"}</dd><dt>Alternate address</dt><dd>${privateAddress?h(privateAddress.alternatePickup||"Not provided"):"Private — reveal access is logged"}</dd><dt>Vehicle</dt><dd>${value(item,"vehicleType")||"Not provided"} · ${item.defaultSeats||3} seats</dd></dl>${privateAddress?"":`<button class="outline" data-reveal="${item.id}">Reveal private addresses (logged)</button>`}${accessHistory(addressLogs)}<button class="${item.approved?"outline":"primary"}" data-approve="${item.id}" data-status="${item.approved?0:1}">${item.approved?"Pause parent access":"Approve parent"}</button></div>`;
    if(kind==="schedule")return `<form id="recordForm"><label>Event type<select name="eventType"><option value="practice" ${item.eventType!=="game"?"selected":""}>Practice</option><option value="game" ${item.eventType==="game"?"selected":""}>Game</option></select></label><label>Event title<input name="title" value="${value(item,"title")}" required></label><div class="two"><label>Date<input name="eventDate" type="date" value="${value(item,"eventDate")}" required></label><label>Event start time<input name="departTime" type="time" value="${value(item,"departTime")}" required></label></div><label>Destination<select name="locationId" required><option value="">Choose a saved location</option>${records.locations.map(location=>`<option value="${location.id}" ${location.id===item.locationId?"selected":""}>${h(location.name)}</option>`).join("")}</select></label>${records.locations.length?"":`<div class="notice">Add a location first, then return to Events.</div>`}<label>Notes<input name="notes" value="${value(item,"notes")}"></label><button class="primary submit" ${records.locations.length?"":"disabled"}>Save record</button></form>`;
    if(kind==="players")return `<form id="recordForm"><label>Player name<input name="name" value="${value(item,"name")}" required></label><label>Parent / guardian<input name="guardian" value="${value(item,"guardian")}" required></label><label>Best contact number<input name="phone" type="tel" value="${value(item,"phone")}" required></label><button class="primary submit">Save record</button></form>`;
    if(kind==="drivers")return `<form id="recordForm"><label>Driver name<input name="parentName" value="${value(item,"parentName")}" required></label><label>Mobile number<input name="phone" type="tel" value="${value(item,"phone")}" required></label><label>Typical available seats<input name="capacity" type="number" min="1" max="8" value="${item.capacity||3}" required></label><label>Driver notes<input name="notes" value="${value(item,"notes")}"></label><button class="primary submit">Save record</button></form>`;
    return `<form id="recordForm"><label>Location name<input name="name" value="${value(item,"name")}" placeholder="Battle Point Park" required></label><label>Google Maps link<input name="mapUrl" type="url" value="${value(item,"mapUrl")}" placeholder="https://maps.app.goo.gl/..." required></label><button class="primary submit">Save record</button></form>`};
  const showTools=()=>{const help=adminHelp[kind]||adminHelp.players;body.innerHTML=`<div class="adminCounts"><span><b>${counts.schedule}</b> events</span><span><b>${counts.players}</b> players</span><span><b>${counts.locations}</b> locations</span><span><b>${profiles.filter(item=>item.approved).length}</b> approved parents</span></div><div class="adminViewTabs"><button class="${view==="manage"?"active":""}" data-view="manage">Manage records</button><button class="${view==="upload"?"active":""}" data-view="upload">Bulk CSV upload</button></div>${view==="upload"?`<div class="importTabs">${Object.keys(adminHelp).map(item=>`<button class="${item===kind?"active":""}" data-kind="${item}">${adminHelp[item].title}</button>`).join("")}</div><form id="adminImport" class="importForm"><h3>Load ${help.title.toLowerCase()} from CSV</h3><p>First row must use these columns:</p><code>${h(help.columns)}</code><small>Example: ${h(help.sample)}</small><label>CSV file<input name="file" type="file" accept=".csv,text/csv" required></label><button class="primary submit">Load CSV</button></form>`:`<div class="importTabs">${[["schedule","Events"],["players","Players"],["drivers","Drivers"],["locations","Locations"],["parents","Parents"]].map(([key,label])=>`<button class="${key===kind?"active":""}" data-kind="${key}">${label}</button>`).join("")}</div>${editing?`<section class="recordEditor"><button class="backButton" data-back>← Back to list</button><h3>${editing.id?`Review ${h(title(editing))}`:`Add ${kind==="schedule"?"event":kind==="players"?"player":kind==="drivers"?"driver profile":"location"}`}</h3>${editor()}${editing.id&&editing.email!==currentUser?.email?`<div class="removeZone">${confirming?`<div><p>This permanently removes this ${kind==="parents"?"parent profile":"record"}${kind==="schedule"?" and its rides and drivers":""}.</p><div><button class="danger" data-remove>Yes, remove it</button><button class="outline" data-cancel>Cancel</button></div></div>`:`<button class="dangerLink" data-confirm>Remove this ${kind==="parents"?"parent profile":"record"}</button>`}</div>`:""}</section>`:`<section class="recordManager"><div class="recordManagerHead"><div><h3>${kind==="schedule"?"Schedule events":kind==="players"?"Player profiles":kind==="drivers"?"Driver profiles":kind==="locations"?"Team locations":"Parent accounts"}</h3><p>Select a record to review, edit, or remove it.</p></div>${kind!=="parents"?`<button class="primary small" data-add>Add new</button>`:""}</div>${list().length?`<div class="recordList">${list().map(item=>`<button data-record="${item.id}"><span><b>${h(title(item))}</b><small>${h(meta(item))}</small></span><strong>Review →</strong></button>`).join("")}</div>`:`<div class="inlineEmpty"><p>No records yet.</p></div>`}</section>`}`}${notice?`<div class="notice" role="status">${h(notice)}</div>`:""}`;
    body.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>{view=button.dataset.view;if(view==="upload")kind="schedule";editing=null;notice="";showTools()}));
    body.querySelectorAll("[data-kind]").forEach(button=>button.addEventListener("click",()=>{kind=button.dataset.kind;editing=null;privateAddress=null;addressLogs=[];confirming=false;notice="";showTools()}));
    body.querySelector("[data-add]")?.addEventListener("click",()=>{editing={};showTools()});body.querySelector("[data-back]")?.addEventListener("click",()=>{editing=null;confirming=false;notice="";showTools()});
    body.querySelectorAll("[data-record]").forEach(button=>button.addEventListener("click",()=>{editing=list().find(item=>String(item.id)===button.dataset.record);privateAddress=null;addressLogs=[];showTools()}));
    body.querySelector("[data-confirm]")?.addEventListener("click",()=>{confirming=true;showTools()});body.querySelector("[data-cancel]")?.addEventListener("click",()=>{confirming=false;showTools()});
    body.querySelector("[data-remove]")?.addEventListener("click",async()=>{try{apply(await adminApi("POST",{action:"delete_record",kind,id:editing.id}));editing=null;confirming=false;notice="Record removed.";if(profile?.approved)await refresh();showTools()}catch(error){notice=error.message;showTools()}});
    body.querySelectorAll("[data-approve]").forEach(button=>button.addEventListener("click",async()=>{try{apply(await adminApi("POST",{action:"set_profile_status",profileId:button.dataset.approve,approved:button.dataset.status==="1"}));editing=profiles.find(item=>String(item.id)===button.dataset.approve)||editing;notice=button.dataset.status==="1"?"Parent approved.":"Parent access paused.";showTools()}catch(error){notice=error.message;showTools()}}));
    body.querySelector("[data-reveal]")?.addEventListener("click",async event=>{try{const result=await adminApi("POST",{action:"reveal_profile_address",profileId:event.target.dataset.reveal,reason:"Administrator reviewed profile addresses"});privateAddress=result.address;addressLogs=result.addressAccessLogs||[];notice="Private addresses revealed and this access was logged.";showTools()}catch(error){notice=error.message;showTools()}});
    body.querySelector("#recordForm")?.addEventListener("submit",async event=>{event.preventDefault();const button=event.target.querySelector("button");button.disabled=true;try{apply(await adminApi("POST",{action:"upsert_record",kind,id:editing.id||0,record:Object.fromEntries(new FormData(event.target))}));editing=null;notice="Record saved.";if(profile?.approved)await refresh();showTools()}catch(error){notice=error.message;showTools()}});
    body.querySelector("#adminImport")?.addEventListener("submit",async event=>{event.preventDefault();const button=event.target.querySelector("button"),file=new FormData(event.target).get("file");button.disabled=true;button.textContent="Loading…";try{const rows=parseCsv(await file.text()),result=await adminApi("POST",{kind,rows});apply(result);notice=`${result.imported} rows loaded.`;if(profile?.approved)await refresh();showTools()}catch(error){notice=error.message;showTools()}});
  };
  modal.querySelector("#adminLogin").addEventListener("submit",async event=>{event.preventDefault();const button=event.target.querySelector("button"),message=event.target.querySelector("#adminNotice");password=new FormData(event.target).get("password");button.disabled=true;button.textContent="Checking…";try{apply(await adminApi());showTools()}catch(error){message.innerHTML=`<div class="notice error">${h(error.message)}</div>`;button.disabled=false;button.textContent="Open admin tools"}});
}

function openProfile(){
  const checks=(data.players||[]).map(player=>`<label><input type="checkbox" name="playerIds" value="${player.id}" ${(profile.playerIds||[]).includes(player.id)?"checked":""}>${h(player.name)}</label>`).join("");
  document.body.insertAdjacentHTML("beforeend",`<div class="modalBackdrop" id="profileModal"><div class="modal"><button class="close">×</button><p class="eyebrow">PRIVATE PARENT PROFILE</p><h2>My profile</h2><p class="privacyCallout">Your exact addresses are hidden from the team directory. They are released only for a ride you request, to its assigned driver, or through logged administrator access.</p><form id="profileForm"><label>Parent name<input name="displayName" value="${h(profile.displayName)}" required></label><label>Mobile number<input name="phone" type="tel" value="${h(profile.phone)}" required></label><label>Home street address<input name="homePickup" value="${h(profile.homePickup)}" placeholder="Street, city, state, ZIP" required></label><label>Alternate private address (optional)<input name="alternatePickup" value="${h(profile.alternatePickup)}" placeholder="Second household, grandparent, etc."></label><label>Vehicle type<input name="vehicleType" value="${h(profile.vehicleType)}" placeholder="Blue Honda Odyssey"></label><label>Typical available seats<input name="defaultSeats" type="number" min="1" max="8" value="${profile.defaultSeats||3}" required></label>${checks?`<fieldset class="playerChecks"><legend>My players</legend>${checks}</fieldset>`:""}${accessHistory(profile.addressAccessLogs)}<div id="profileNotice"></div><button class="primary submit">Save profile</button></form></div></div>`);
  const modal=document.querySelector("#profileModal");modal.querySelector(".close").addEventListener("click",()=>modal.remove());modal.addEventListener("click",event=>{if(event.target===modal)modal.remove()});modal.querySelector("form").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.target),button=event.target.querySelector("button");button.disabled=true;try{const body={displayName:form.get("displayName"),phone:form.get("phone"),homePickup:form.get("homePickup"),alternatePickup:form.get("alternatePickup"),vehicleType:form.get("vehicleType"),defaultSeats:form.get("defaultSeats"),playerIds:form.getAll("playerIds")},response=await fetch(PROFILE_API,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${idToken}`},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error);const reload=await fetch(PROFILE_API,{headers:{authorization:`Bearer ${idToken}`}}),payload=await reload.json();profile=payload.profile;modal.remove();profile.approved?await refresh("Profile updated."):pending()}catch(error){event.target.querySelector("#profileNotice").innerHTML=`<div class="notice error">${h(error.message)}</div>`;button.disabled=false}})
}

function openDirectory(){const players=new Map(data.players.map(item=>[item.id,item.name]));document.body.insertAdjacentHTML("beforeend",`<div class="modalBackdrop" id="directoryModal"><div class="modal directoryModal"><button class="close">×</button><p class="eyebrow">SIGNED-IN FAMILIES ONLY</p><h2>Team directory</h2><p class="privacyCallout">Home addresses stay private and are shared only with an assigned driver for an active ride.</p><div class="directoryGrid">${(data.directory||[]).map(item=>`<article><div class="avatar">${h(initials(item.displayName))}</div><div><h3>${h(item.displayName)}</h3><p>${h(item.phone)}</p><dl><dt>Pickup privacy</dt><dd>Private — assigned drivers only</dd><dt>Vehicle</dt><dd>${h(item.vehicleType||"Not provided")} · ${item.defaultSeats} seats</dd>${item.playerIds?.length?`<dt>Players</dt><dd>${h(item.playerIds.map(id=>players.get(id)).filter(Boolean).join(", "))}</dd>`:""}</dl></div></article>`).join("")}</div></div></div>`);const modal=document.querySelector("#directoryModal");modal.querySelector(".close").addEventListener("click",()=>modal.remove());modal.addEventListener("click",event=>{if(event.target===modal)modal.remove()})}

const field = (name,label,type="text",placeholder="",required=true) => `<label>${label}<input name="${name}" type="${type}" placeholder="${h(placeholder)}" ${required?"required":""}></label>`;
const trip = () => `<label>Trip<select name="direction"><option value="roundtrip">Round trip</option><option value="to">Drop-off</option><option value="from">Pickup / ride home</option></select></label>`;
const eventOptions = () => data.events.map(item=>`<option value="${item.id}" ${item.id===selected?"selected":""}>${item.eventType==="practice"?"Practice":"Game"}: ${h(item.title)} · ${h(shortDate(item.eventDate))}</option>`).join("");

function openModal(kind) {
  if ((kind==="driver"||kind==="ride")&&!data.events.length)return;
  const titles={player:"Add a player",driver:"Volunteer to drive",ride:"Request a ride"};
  const eligiblePlayers=(data.players||[]).filter(player=>(profile.playerIds||[]).includes(player.id));
  let fields="";
  if(kind==="player") fields=`${field("name","Player name")}${field("guardian","Parent / guardian")}${field("phone","Best contact number","tel")}`;
  if(kind==="driver") fields=`<label>Game or practice<select name="eventId">${eventOptions()}</select></label>${field("parentName","Driver name")}${field("phone","Mobile number","tel")}<div class="two">${trip()}${field("capacity","Open seats","number")}</div>${field("notes","Pickup notes","text","Can meet at the school",false)}`;
  if(kind==="ride") fields=`<label>Game or practice<select name="eventId">${eventOptions()}</select></label>${eligiblePlayers.length?`<label>Player<select name="playerId" required><option value="">Select a player</option>${eligiblePlayers.map(p=>`<option value="${p.id}">${h(p.name)}</option>`).join("")}</select></label>`:`<div class="notice">Add or connect your player before requesting a ride.</div><button type="button" class="outline" data-add-player>Add player</button>`}<label>Pickup location<select name="pickupChoice" data-pickup required><option value="">Choose a pickup location</option>${profile.homePickup?`<option value="home">My home address — private</option>`:""}${profile.alternatePickup?`<option value="alternate">My alternate address — private</option>`:""}${(data.locations||[]).map(item=>`<option value="location:${item.id}">${h(item.name)} — common location</option>`).join("")}<option value="override">One-time different address — private</option></select></label><div data-override></div><small class="privateNote">Private addresses are visible only to the assigned driver and in logged administrator access.</small>${trip()}${field("notes","Notes","text","Booster seat, timing, etc.",false)}`;
  document.body.insertAdjacentHTML("beforeend",`<div class="modalBackdrop" id="modal"><div class="modal"><button class="close" aria-label="Close">×</button><p class="eyebrow">TEAM RIDE BOARD</p><h2>${titles[kind]}</h2><form id="modalForm">${fields}<button class="primary submit" ${(kind==="ride"&&!eligiblePlayers.length)?"disabled":""}>${kind==="player"?"Save player":kind==="driver"?"Offer seats":"Request ride"}</button></form></div></div>`);
  const modal=document.querySelector("#modal");
  modal.querySelector(".close").addEventListener("click",()=>modal.remove());
  modal.addEventListener("click",event=>{if(event.target===modal)modal.remove()});
  modal.querySelector("[data-add-player]")?.addEventListener("click",()=>{modal.remove();openModal("player")});
  modal.querySelector("[data-pickup]")?.addEventListener("change",event=>{modal.querySelector("[data-override]").innerHTML=event.target.value==="override"?field("overrideAddress","One-time pickup street address","text","Street, city, state, ZIP"):""});
  modal.querySelector("#modalForm").addEventListener("submit",async event=>{
    event.preventDefault();
    const action=kind==="player"?"add_player":kind==="driver"?"volunteer":"request_ride";
    try{await api("POST",{action,...Object.fromEntries(new FormData(event.target))});modal.remove();await refresh("Roster updated.");}
    catch(error){alert(error.message)}
  });
}

async function refresh(notice=""){idToken=await currentUser.getIdToken();data=await api();if(!data.events.some(event=>event.id===selected))selected=data.events[0]?.id||null;render(notice)}

firebase.initializeApp(firebaseConfig);
firebase.auth().onAuthStateChanged(async user=>{currentUser=user;if(!user){idToken="";profile=null;login();return}try{idToken=await user.getIdToken();const response=await fetch(PROFILE_API,{headers:{authorization:`Bearer ${idToken}`}}),payload=await response.json();if(!response.ok)throw new Error(payload.error);profile=payload.profile;if(!profile.approved){pending();return}data=await api();selected=data.events[0]?.id||null;render()}catch(error){login(error.message)}});
